version: 2.1

parameters:
  site:
    type: string
    default: "divd.fund"

jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build and check
          command: |
            echo "*** Building and checking ***"; 
            gem install jekyll-environment-variables
            jekyll build 2>&1
            ./proof_html.sh 
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/_site"
            - "/root/project/.htaccess"
      - store_artifacts:
          path: /root/project/_site


  upload:
    docker:
      - image: alpine:latest
    environment:
      SITE: << pipeline.parameters.site >>
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh;
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Upload
          command: |
            mkdir -p ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/_site;
            rsync -av --delete . www-divd@upload.bit.nl:htdocs/$SITE;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - main
